import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type User = { id: string; displayName: string; factorioName: string; color: string };
type Dashboard = {
  appUptimeSeconds: number;
  snapshot: { generatedAt: string; server: { online: boolean; version: string | null; gameState: string; uptimeSeconds: number | null; lastSaveAt: string | null }; players: Array<{ factorioName: string; online: boolean; lastOnlineAt: string | null; playtimeSeconds: number; personalActivity: { handCrafted: number; mined: number; built: number; deaths: number } }>; sharedFactory: Array<{ item: string; produced: number; consumed: number }>; events: Array<{ id: string; type: string; occurredAt: string; message: string }> };
  tasks: Array<{ id: string; title: string; status: string; priority: number; location: string | null }>;
  activity: Array<{ event_type: string; payload_json: string; occurred_at: string }>;
};
type Profile = { id: string; displayName: string; factorioName: string; color: string; online: boolean; lastOnlineAt: string | null; playtimeSeconds: number; completedTasks: number; personalActivity: { handCrafted: number; mined: number; built: number; deaths: number } };
type Task = { id: string; title: string; description: string; status: 'Now' | 'Next' | 'Later' | 'Done'; priority: number; location: string | null; tags: string[]; assigneeIds: string[] };
type TaskDetail = Task & { blueprint_string: string | null; checklist: Array<{ id: string; text: string; isDone: boolean }>; comments: Array<{ id: string; body: string; created_at: string; display_name: string }>; history: Array<{ id: string; action: string; created_at: string; display_name: string; detail: Record<string, unknown> }> };
type Activity = { id: string; source: string; event_type: string; occurred_at: string; actor_name: string | null; payload: { message?: string; title?: string; from?: string; to?: string } };
type Production = { range: string; points: Array<{ at: string; productionRate: number; consumptionRate: number }>; topItems: Array<{ item: string; produced: number; consumed: number }> };

let csrfToken = '';
async function api<T>(path: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(path, { ...init, headers: { 'content-type': 'application/json', ...(init.method && init.method !== 'GET' ? { 'x-csrf-token': csrfToken } : {}), ...init.headers } });
  if (!response.ok) throw new Error((await response.json().catch(() => ({ error: 'Request failed.' }))).error);
  return response.status === 204 ? undefined as T : response.json();
}
const duration = (seconds: number | null) => seconds === null ? '—' : `${Math.floor(seconds / 3600)} h ${Math.floor(seconds / 60) % 60} min`;
const timeAgo = (value: string | null) => !value ? '—' : new Intl.RelativeTimeFormat('cs', { numeric: 'auto' }).format(Math.round((new Date(value).getTime() - Date.now()) / 60_000), 'minute');

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [login, setLogin] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError('');
    try { const result = await api<{ csrfToken: string }>('/api/auth/login', { method: 'POST', body: JSON.stringify({ login, password }) }); csrfToken = result.csrfToken; const session = await api<{ user: User }>('/api/auth/session'); onLogin(session.user); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Přihlášení se nezdařilo.'); }
  }
  return <main className="login-shell"><form className="login-card" onSubmit={submit}><p className="eyebrow">HAL-1000 / PRIVATE</p><h1>Factory Control</h1><p>Správa společné továrny pro dva operátory.</p><label>Login<input autoComplete="username" value={login} onChange={e => setLogin(e.target.value)} /></label><label>Heslo<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button>Přihlásit se</button></form></main>;
}

function Nav({ active, setActive }: { active: string; setActive: (value: string) => void }) {
  return <nav>{['Dashboard', 'Tasks', 'Production', 'Activity', 'Profiles', 'Server'].map(item => <button className={active === item ? 'active' : ''} key={item} onClick={() => setActive(item)}>{item}</button>)}</nav>;
}

function DashboardView({ data, refresh }: { data: Dashboard; refresh: () => void }) {
  const server = data.snapshot.server;
  return <section className="content"><header className="page-title"><div><p className="eyebrow">LIVE OVERVIEW</p><h1>Factory dashboard</h1></div><button className="secondary" onClick={refresh}>Obnovit data</button></header>
    <div className="status-row"><article className="server-state"><span className={server.online ? 'lamp online' : 'lamp'}></span><div><strong>{server.online ? 'Server online' : 'Server offline'}</strong><small>{server.version ?? 'Verze zatím neznámá'} · {server.gameState}</small></div></article><Metric label="Uptime aplikace" value={duration(data.appUptimeSeconds)} /><Metric label="Poslední save" value={timeAgo(server.lastSaveAt)} /><Metric label="Herní uptime" value={duration(server.uptimeSeconds)} /></div>
    <div className="grid split"><Panel title="Připojení hráči"><div className="players">{data.snapshot.players.map(player => <div className="player" key={player.factorioName}><span className={player.online ? 'dot online' : 'dot'}></span><div><strong>{player.factorioName}</strong><small>{player.online ? 'online' : `naposledy ${timeAgo(player.lastOnlineAt)}`}</small></div><span>{duration(player.playtimeSeconds)}</span></div>)}</div></Panel><Panel title="Prioritní úkoly">{data.tasks.length ? <ul className="tasks">{data.tasks.map(task => <li key={task.id}><b className={`priority p${task.priority}`}>P{task.priority}</b><div><strong>{task.title}</strong><small>{task.status}{task.location ? ` · ${task.location}` : ''}</small></div></li>)}</ul> : <p className="muted">Zatím žádné otevřené úkoly.</p>}</Panel></div>
    <Panel title="Shared factory · kumulativní produkce"><div className="chart"><ResponsiveContainer width="100%" height={260}><BarChart data={data.snapshot.sharedFactory}><CartesianGrid strokeDasharray="3 3" stroke="#313a3b"/><XAxis dataKey="item" tickFormatter={value => value.replaceAll('-', ' ')} stroke="#a7b1af"/><YAxis stroke="#a7b1af"/><Tooltip contentStyle={{ background: '#171c1d', border: '1px solid #394344' }}/><Bar dataKey="produced" name="Vyrobeno" fill="#e69636" radius={[3,3,0,0]}/><Bar dataKey="consumed" name="Spotřebováno" fill="#5fa99b" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div><FactoryItems items={data.snapshot.sharedFactory} /></Panel>
    <Panel title="Poslední události"><ul className="activity">{data.snapshot.events.map(event => <li key={event.id}><time>{timeAgo(event.occurredAt)}</time><span>{event.message}</span></li>)}</ul></Panel>
  </section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <article className="metric"><small>{label}</small><strong>{value}</strong></article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <article className="panel"><h2>{title}</h2>{children}</article>; }
function itemLabel(prototype: string) { return prototype.replaceAll('-', ' '); }
function ItemIcon({ prototype }: { prototype: string }) { const [missing, setMissing] = useState(false); return missing ? <span className="item-icon fallback" aria-label={`${itemLabel(prototype)} – ikona není nainstalována`}>◆</span> : <img className="item-icon" src={`/api/icons/${encodeURIComponent(prototype)}`} alt="" onError={() => setMissing(true)} />; }
function FactoryItems({ items }: { items: Array<{ item: string }> }) { return <div className="factory-items">{items.map(item => <span key={item.item}><ItemIcon prototype={item.item} /><small>{itemLabel(item.item)}</small></span>)}</div>; }

function TasksView({ onChanged }: { onChanged: () => void }) {
  const [tasks, setTasks] = useState<Task[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]); const [title, setTitle] = useState(''); const [status, setStatus] = useState<Task['status']>('Next'); const [priority, setPriority] = useState(2); const [assignees, setAssignees] = useState<string[]>([]); const [error, setError] = useState(''); const [selected, setSelected] = useState<string | null>(null);
  const load = () => Promise.all([api<Task[]>('/api/tasks'), api<Profile[]>('/api/profiles')]).then(([loadedTasks, loadedProfiles]) => { setTasks(loadedTasks); setProfiles(loadedProfiles); setAssignees(current => current.length ? current : loadedProfiles.map(profile => profile.id)); });
  useEffect(() => { void load().catch(reason => setError(reason.message)); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); try { await api('/api/tasks', { method: 'POST', body: JSON.stringify({ title, status, priority, assigneeIds: assignees }) }); setTitle(''); await load(); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Úkol se nepodařilo vytvořit.'); } }
  async function move(id: string, next: Task['status']) { try { await api(`/api/tasks/${id}/status`, { method: 'PATCH', body: JSON.stringify({ status: next }) }); await load(); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Změna se nezdařila.'); } }
  return <section className="content"><header className="page-title"><div><p className="eyebrow">SHARED BOARD</p><h1>Tasks</h1></div></header>{error && <p className="error">{error}</p>}<Panel title="Nový úkol"><form className="task-form" onSubmit={create}><input placeholder="Co je potřeba udělat?" value={title} onChange={event => setTitle(event.target.value)} required /><select value={status} onChange={event => setStatus(event.target.value as Task['status'])}>{['Now','Next','Later','Done'].map(value => <option key={value}>{value}</option>)}</select><select value={priority} onChange={event => setPriority(Number(event.target.value))}>{[1,2,3,4].map(value => <option key={value} value={value}>Priorita {value}</option>)}</select><div className="assignees">{profiles.map(profile => <label key={profile.id}><input type="checkbox" checked={assignees.includes(profile.id)} onChange={() => setAssignees(current => current.includes(profile.id) ? current.filter(value => value !== profile.id) : [...current, profile.id])}/>{profile.displayName}</label>)}</div><button>Vytvořit úkol</button></form></Panel><div className="board">{(['Now','Next','Later','Done'] as const).map(column => <article className="board-column" key={column}><h2>{column}<span>{tasks.filter(task => task.status === column).length}</span></h2>{tasks.filter(task => task.status === column).map(task => <div className="task-card" role="button" tabIndex={0} onClick={() => setSelected(task.id)} onKeyDown={event => event.key === 'Enter' && setSelected(task.id)} key={task.id}><b className={`priority p${task.priority}`}>P{task.priority}</b><strong>{task.title}</strong>{task.description && <p>{task.description}</p>}{task.tags.length > 0 && <small>{task.tags.map(tag => `#${tag}`).join(' ')}</small>}<select aria-label={`Stav ${task.title}`} value={task.status} onClick={event => event.stopPropagation()} onChange={event => void move(task.id, event.target.value as Task['status'])}>{['Now','Next','Later','Done'].map(value => <option key={value}>{value}</option>)}</select></div>)}</article>)}</div>{selected && <TaskDetailView id={selected} onClose={() => setSelected(null)} onChanged={() => { void load(); onChanged(); }} />}</section>;
}

function TaskDetailView({ id, onClose, onChanged }: { id: string; onClose: () => void; onChanged: () => void }) {
  const [task, setTask] = useState<TaskDetail | null>(null); const [checkText, setCheckText] = useState(''); const [comment, setComment] = useState(''); const [error, setError] = useState('');
  const load = () => api<TaskDetail>(`/api/tasks/${id}`).then(setTask);
  useEffect(() => { void load().catch(reason => setError(reason.message)); }, [id]);
  async function addChecklist(event: React.FormEvent) { event.preventDefault(); try { await api(`/api/tasks/${id}/checklist`, { method: 'POST', body: JSON.stringify({ text: checkText }) }); setCheckText(''); await load(); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Checklist se nezdařil.'); } }
  async function toggle(itemId: string, isDone: boolean) { try { await api(`/api/tasks/${id}/checklist/${itemId}`, { method: 'PATCH', body: JSON.stringify({ isDone }) }); await load(); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Změna se nezdařila.'); } }
  async function addComment(event: React.FormEvent) { event.preventDefault(); try { await api(`/api/tasks/${id}/comments`, { method: 'POST', body: JSON.stringify({ body: comment }) }); setComment(''); await load(); onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Komentář se nezdařil.'); } }
  return <div className="task-detail-backdrop" role="dialog" aria-modal="true"><article className="task-detail"><button className="detail-close" onClick={onClose}>Zavřít</button>{error && <p className="error">{error}</p>}{!task ? <p className="muted">Načítám úkol…</p> : <><p className="eyebrow">{task.status} · PRIORITA {task.priority}</p><h2>{task.title}</h2><p>{task.description || 'Bez popisu.'}</p>{task.blueprint_string && <section><h3>Blueprint</h3><button className="secondary" onClick={() => void navigator.clipboard.writeText(task.blueprint_string!)}>Kopírovat blueprint string</button></section>}<section><h3>Checklist</h3><ul className="checklist">{task.checklist.map(item => <li key={item.id}><label><input type="checkbox" checked={item.isDone} onChange={event => void toggle(item.id, event.target.checked)} />{item.text}</label></li>)}</ul><form className="inline-form" onSubmit={addChecklist}><input value={checkText} onChange={event => setCheckText(event.target.value)} placeholder="Přidat položku checklistu" required/><button>Přidat</button></form></section><section><h3>Komentáře</h3>{task.comments.map(entry => <p className="comment" key={entry.id}><strong>{entry.display_name}</strong> · {entry.body}</p>)}<form className="inline-form" onSubmit={addComment}><input value={comment} onChange={event => setComment(event.target.value)} placeholder="Napsat komentář" required/><button>Odeslat</button></form></section><section><h3>Historie</h3><ul className="history">{task.history.map(entry => <li key={entry.id}>{entry.display_name} · {entry.action} · {timeAgo(entry.created_at)}</li>)}</ul></section></>}</article></div>;
}

function ProfilesView() {
  const [profiles, setProfiles] = useState<Profile[]>([]); const [error, setError] = useState('');
  useEffect(() => { void api<Profile[]>('/api/profiles').then(setProfiles).catch(reason => setError(reason.message)); }, []);
  return <section className="content"><header className="page-title"><div><p className="eyebrow">OPERATORS</p><h1>Profiles</h1></div></header>{error && <p className="error">{error}</p>}<div className="profile-grid">{profiles.map(profile => <article className="profile-card" key={profile.id}><div className="avatar" style={{ background: profile.color }}>{profile.displayName.slice(0, 1)}</div><div><h2>{profile.displayName}</h2><p>{profile.factorioName} <span className={profile.online ? 'online-label' : ''}>{profile.online ? 'online' : 'offline'}</span></p></div><div className="profile-stats"><Metric label="Playtime" value={duration(profile.playtimeSeconds)} /><Metric label="Hotové úkoly" value={String(profile.completedTasks)} /><Metric label="Ručně vyrobeno" value={String(profile.personalActivity.handCrafted)} /><Metric label="Postaveno" value={String(profile.personalActivity.built)} /></div></article>)}</div></section>;
}

function ActivityView() {
  const [events, setEvents] = useState<Activity[]>([]); const [error, setError] = useState('');
  useEffect(() => { void api<Activity[]>('/api/activity').then(setEvents).catch(reason => setError(reason.message)); }, []);
  return <section className="content"><header className="page-title"><div><p className="eyebrow">EVENT STREAM</p><h1>Activity</h1></div></header>{error && <p className="error">{error}</p>}<Panel title="Posledních 100 událostí"><ul className="activity full">{events.map(event => <li key={event.id}><time>{timeAgo(event.occurred_at)}</time><div><strong>{event.payload.message ?? event.payload.title ?? event.event_type}</strong><small>{event.actor_name ? `${event.actor_name} · ` : ''}{event.source} {event.payload.from ? `· ${event.payload.from} → ${event.payload.to}` : ''}</small></div></li>)}{events.length === 0 && <li className="muted">Zatím nejsou žádné události.</li>}</ul></Panel></section>;
}

function ProductionView() {
  const [range, setRange] = useState('1h'); const [production, setProduction] = useState<Production | null>(null); const [error, setError] = useState('');
  useEffect(() => { setProduction(null); void api<Production>(`/api/production?range=${range}`).then(setProduction).catch(reason => setError(reason.message)); }, [range]);
  return <section className="content"><header className="page-title"><div><p className="eyebrow">SHARED FACTORY</p><h1>Production</h1></div><div className="range-picker">{['15m','1h','6h','24h'].map(value => <button className={range === value ? '' : 'secondary'} key={value} onClick={() => setRange(value)}>{value}</button>)}</div></header>{error && <p className="error">{error}</p>}<Panel title="Production a consumption rate / min"><div className="chart">{production && <ResponsiveContainer width="100%" height={340}><LineChart data={production.points}><CartesianGrid strokeDasharray="3 3" stroke="#313a3b"/><XAxis dataKey="at" tickFormatter={value => new Date(value).toLocaleTimeString('cs', { hour: '2-digit', minute: '2-digit' })} minTickGap={30} stroke="#a7b1af"/><YAxis stroke="#a7b1af"/><Tooltip labelFormatter={value => new Date(String(value)).toLocaleString('cs')} contentStyle={{ background: '#171c1d', border: '1px solid #394344' }}/><Line type="monotone" dataKey="productionRate" name="Výroba/min" stroke="#e69636" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="consumptionRate" name="Spotřeba/min" stroke="#5fa99b" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer>}</div></Panel><div className="grid split"><Panel title="Nejvíce vyráběné"><TopItems items={production?.topItems ?? []} metric="produced" /></Panel><Panel title="Nejvíce spotřebovávané"><TopItems items={production?.topItems ?? []} metric="consumed" /></Panel></div><p className="muted">Strojová výroba je vždy společná pro force/továrnu; osobní aktivita patří pouze do Profiles.</p></section>;
}
function TopItems({ items, metric }: { items: Production['topItems']; metric: 'produced' | 'consumed' }) { return <ul className="top-items">{[...items].sort((a, b) => b[metric] - a[metric]).slice(0, 5).map(item => <li key={item.item}><span className="item-name"><ItemIcon prototype={item.item} />{itemLabel(item.item)}</span><strong>{item[metric].toLocaleString('cs')}</strong></li>)}{items.length === 0 && <li className="muted">Čekám na druhý telemetry vzorek.</li>}</ul>; }

function ServerView({ onChanged }: { onChanged: () => void }) {
  const [message, setMessage] = useState(''); const [notice, setNotice] = useState('');
  async function save() { try { await api('/api/server/save', { method: 'POST' }); setNotice('Save příkaz byl odeslán a zaznamenán.'); onChanged(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Save se nezdařil.'); } }
  async function refreshTelemetry() { try { await api('/api/server/telemetry-refresh', { method: 'POST' }); setNotice('Telemetry byla obnovena a zaznamenána.'); onChanged(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Obnovení se nezdařilo.'); } }
  async function send(event: React.FormEvent) { event.preventDefault(); try { await api('/api/server/message', { method: 'POST', body: JSON.stringify({ message }) }); setMessage(''); setNotice('Zpráva byla odeslána a zaznamenána.'); onChanged(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : 'Zpráva se nezdařila.'); } }
  return <section className="content"><header className="page-title"><div><p className="eyebrow">SAFE CONTROLS</p><h1>Server</h1></div></header><Panel title="Povolené akce"><p className="muted">Neexistuje zde raw RCON konzole. Všechny mutující akce se auditují.</p><div className="server-actions"><button onClick={() => void save()}>Spustit save</button><button className="secondary" onClick={() => void refreshTelemetry()}>Obnovit telemetry</button><form onSubmit={send}><input placeholder="Zpráva do hry" maxLength={250} value={message} onChange={event => setMessage(event.target.value)} required/><button>Odeslat zprávu</button></form></div>{notice && <p className="muted">{notice}</p>}</Panel></section>;
}

export function App() {
  const [user, setUser] = useState<User | null>(null); const [data, setData] = useState<Dashboard | null>(null); const [active, setActive] = useState('Dashboard'); const [error, setError] = useState('');
  const load = async () => { try { setData(await api<Dashboard>('/api/dashboard')); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Data nejsou dostupná.'); } };
  useEffect(() => { api<{ user: User; csrfToken: string }>('/api/auth/session').then(session => { csrfToken = session.csrfToken; setUser(session.user); }).catch(() => undefined); }, []);
  useEffect(() => { if (user) void load(); }, [user]);
  const content = useMemo(() => !data ? <div className="loading">Načítám provoz továrny…</div> : active === 'Dashboard' ? <DashboardView data={data} refresh={() => void load()} /> : active === 'Tasks' ? <TasksView onChanged={() => void load()} /> : active === 'Production' ? <ProductionView /> : active === 'Activity' ? <ActivityView /> : active === 'Profiles' ? <ProfilesView /> : <ServerView onChanged={() => void load()} />, [active, data]);
  if (!user) return <Login onLogin={setUser} />;
  return <main className="app-shell"><aside><div className="brand"><span>H</span><div><strong>HAL Factory</strong><small>{user.displayName}</small></div></div><Nav active={active} setActive={setActive}/><button className="logout" onClick={() => api('/api/auth/logout', { method: 'POST' }).finally(() => { csrfToken = ''; setUser(null); setData(null); })}>Odhlásit</button></aside><div className="main">{error && <div className="error banner">{error}</div>}{content}</div></main>;
}
